# Generated by Django 5.1.7 on 2025-04-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intership',
            old_name='address',
            new_name='university',
        ),
    ]
