# Generated by Django 5.1.7 on 2025-03-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
